apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-lucifer
  name: ums-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ums-pod
  template:
    metadata:
      labels:
        app: ums-pod
    spec:
      containers:
        - name: ums
          image: $image
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
      imagePullSecrets:
        - name: harbor-login
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-lucifer
  name: ums-service
spec:
  selector:
    app: ums-pod
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30102
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.137.136

#apiVersion: v1
#kind: Service
#metadata:
#  namespace: kube-lucifer
#  name: ums-service
#spec:
#  selector:
#    app: ums-pod
#  ports:
#    - port: 8082
#      targetPort: 8082
#  clusterIP: None
#  type: ClusterIP


